### ISSUE TITLE
Having trouble installing the tested versions of NumPy and Pandas in a Jupyter Notebook custom environment

### ISSUE THREAD

**Issue by Franz4272** [flyark/AFM-LIS#1]
Hi,

I hope this message finds you well. I am having trouble installing the tested versions of NumPy and Pandas in a Jupyter Notebook custom environment with the tested version of python. The tested version of biopython was installed without a problem.  

`!conda create --name AFM_LIS python=3.6.7 ipykernel -y`
`!conda install numpy=1.19.4 pandas=1.1.4 biopython=1.78 -y`
`Channels:`
` - defaults`
`Platform: linux-64`
`Collecting package metadata (repodata.json): done`
`Solving environment: failed`
`PackagesNotFoundError: The following packages are not available from current channels:`
` - numpy=1.19.4*`
` - pandas=1.1.4*`
`Current channels:`
`  - defaults`

Can I run AFM-LIS with the most up-to-date versions of python, NumPy, and Pandas? Do I need to install openpyxl as well for the excel files? Please let me know the best way to install the required packages when you have time. 

Thank you,
Franz

**Comment by Franz4272** [comment]
AFM_LIS appears to be working after installing openpyxl=3.0.9 in a custom environment with python=3.6.7, biopython=1.78, numpy=1.19.2, and pandas =1.1.5. I am using the script for inputs from ColabFold. I am not sure If there is something better you would recommend. Please let me know what you think.

Thank you,
Franz

**Comment by flyark** [comment]
Hi Franz, 

Thanks for letting me know this! 

Since I have been using the jupyter notebook in the school server, I haven't notice such issue. I will mention the version of openpyxl I am using to the requirement in README. 

I wish this notebook is helpful for your PPI prediction! 

Best, 
Ah-Ram

**Comment by Franz4272** [comment]
Yes, it definitely will be! Thank you for making it!
