### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by AASTHAPAL9** [flyark/AFM-LIS#2]
Hi,

I was able to create a virtual env and installed all the libraries with the specified version however, I still couldn't get Bio installed. 

Secondly, I tried the notebook for colabfold outputs and I specified the separator that I used in my fasta file to separate the two proteins, I am still getting empty lists. I wonder what else is to be considered for running this script. 

These are the outputs: 
![Screenshot 2024-04-21 at 4 04 30 PM](https://github.com/flyark/AFM-LIS/assets/98487751/6c20da09-9d51-4195-847b-4f3933275095)

`# Change if different separator is used for distinguishing protein_1 and protein_2
    if file_name.count(":") == 1:
        protein_1 = file_name.split(":")[0]
        protein_2_temp = file_name.split(":")[1]
        protein_2 = protein_2_temp.split("_unrelaxed")[0]
    else:
        print(f"Warning: Unexpected file naming convention for {file_name}. Skipping this file.")
        return None  # or some other default behavior`

**Comment by flyark** [comment]
Hi, I added "name_separator" in alphafold_interaction_scores_github_20240421.ipynb. 
for biopython installation, you may be able to install by "pip install biopython==1.78" in the terminal (activating your python env).

**Comment by AASTHAPAL9** [comment]
Hi @flyark, thank you for quick update. It is still empty. I made a change in the name_separator.

**Comment by flyark** [comment]
Hi, could you share these three?  
**base_path
saving_base_path 
folders_to_analyze**

there might be some issue with file variable.

**Comment by AASTHAPAL9** [comment]
Hi @flyark. Could you share you email?

**Comment by flyark** [comment]
ah-ram_kim@hms.harvard.edu

**Comment by flyark** [comment]
@AASTHAPAL9 please email me via the above email.
